# Generated by Django 4.0.1 on 2022-01-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
