# Generated by Django 4.0.1 on 2022-01-30 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctordashboard', '0003_alter_appointment_cause_alter_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
